stages:
  - test
  - sbom

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_TAG

default:
  tags:
    - flarenetwork
  artifacts:
    expire_in: 3 days

variables:
  GO_VERSION: "1.26.8"
  GOVULNCHECK_VERSION: "v1.6.0"

vuln:
  stage: test
  image: mirror.gcr.io/golang:${GO_VERSION}
  interruptible: true
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
  before_script:
    - mkdir -p ${GOPATH}
  cache:
    paths:
      - ${GOPATH}/pkg/mod/
      - ${GOPATH}/bin
  script:
    - go run golang.org/x/vuln/cmd/govulncheck@${GOVULNCHECK_VERSION} ./...

include:
  - component: gitlab.com/flarenetwork/ci-components-private/lgtm@2
  - component: gitlab.com/flarenetwork/ci-components-private/dependency-track@2
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - component: gitlab.com/flarenetwork/ci-components-private/lint-dockerfile@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-go@2
    inputs:
      go_version: "${GO_VERSION}"
      golangci_version: "v2.13.2"
      golangci_config_file: ".golangci.yml"
  - component: gitlab.com/flarenetwork/ci-components-private/test-go@2
    inputs:
      go_version: "${GO_VERSION}"
      go_test_command: "go test -v -race -covermode=atomic -coverprofile=coverage.out -coverpkg=./... ./..."
      tags: ["flarenetwork-lg"]
  - component: gitlab.com/flarenetwork/ci-components-private/test-docker-build@2
